name = "app"
target = "javascript"

[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glen = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_javascript = ">= 0.12.0 and < 1.0.0"
gleam_fetch = ">= 1.0.1 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
envoy = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
